### ISSUE TITLE
Money for assassination should sometimes be returned to the player

### ISSUE THREAD

**Issue by einsteinsfool** [octachrome/treason#13]
According to [author of the game](https://boardgamegeek.com/article/10440845#10440845), when somebody blocks assassin or challenges him successfully, $3 are returned to the player who claimed assassin.

// I decided to report all bugs/requests that I found, so other people might work on them as well. And perhaps I won't be able to fix some issues myself.

**Comment by octachrome** [comment]
You are right. This one has been on my list for a while but I haven't got around to fixing it...
