### ISSUE TITLE
AIs take income even when 3 dukes are out

### ISSUE THREAD

**Issue by ThisIsSoNotMe** [octachrome/treason#25]
When 3 dukes are revealed, the AI takes income instead of foreign aid despite the fact that foreign aid is perfectly safe to take. 
(Edit: I've realized this is similar to #21, however the AIs can be sure that foreign aid is safe to take in this scenario)
(Edit 2: I've now realized that there was an attempt to fix this issue https://github.com/octachrome/treason/pull/18. I'll try to get a screenshot of the AIs acting in this way)

**Comment by ThisIsSoNotMe** [comment]
![screen shot 2019-02-16 at 12 01 48](https://user-images.githubusercontent.com/13316627/52899695-cf325e80-31e4-11e9-8386-763f721f2640.png)

**Comment by octachrome** [comment]
Thanks for the issue report. Sorry I haven't replied earlier, I've not had any time for this project recently. It is odd that this issue still exists given the fix for #18.

**Comment by NobleUplift** [comment]
According to [version.js](http://treason.thebrown.net/version.js), the site is still running `v0.1.8-160-gfed5832`, was the fixed pushed to production?

**Comment by octachrome** [comment]
Good point! This is now pushed.
