### ISSUE TITLE
Issue running server

### ISSUE THREAD

**Issue by ndo360** [octachrome/treason#3]
Hello! I've been trying to host a server and i'm having this issue when I try to run server.js 

Here is the error:

C:\Users\17clinen\Desktop\treason-master>node server.js
(node:3448) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 1): Error: not initialized
(node:3448) DeprecationWarning: Unhandled promise rejections are deprecated. In
the future, promise rejections that are not handled will terminate the Node.js p
rocess with a non-zero exit code.
Failed to initialise database(s)
{ Error: connect ECONNREFUSED 127.0.0.1:5984
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5984 }

Anyone know how to fix this?

**Comment by octachrome** [comment]
@ndo360 This is because it can't connect to couchdb. I guess you don't have it installed? The readme is very out of date - sorry about that.

**Comment by ndo360** [comment]
Can you update the readme and link to couchdb?

**Comment by octachrome** [comment]
Yeah I will at some point. There are many things that need updating.

**Comment by ndo360** [comment]
I have ran this command: 'npm install node-couchdb --save' inside the treason-master directroy and this happened:

C:\Users\17clinen\Desktop\treason-master>npm install node-couchdb --save
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie h
ttps://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
treason@0.0.0 C:\Users\17clinen\Desktop\treason-master
`-- node-couchdb@1.1.0
  `-- request@2.70.0
    +-- bl@1.1.2
    | `-- readable-stream@2.0.6
    |   `-- isarray@1.0.0
    +-- extend@3.0.0
    +-- form-data@1.0.1
    | `-- async@2.1.4
    +-- node-uuid@1.4.7
    +-- qs@6.1.0
    `-- tough-cookie@2.2.2

npm WARN treason@0.0.0 No repository field.

I then tried to host the server and it still failed:

C:\Users\17clinen\Desktop\treason-master>node server.js
(node:3300) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 1): Error: not initialized
(node:3300) DeprecationWarning: Unhandled promise rejections are deprecated. In
the future, promise rejections that are not handled will terminate the Node.js p
rocess with a non-zero exit code.
Failed to initialise database(s)
{ Error: connect ECONNREFUSED 127.0.0.1:5984
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5984 }

Any other suggestions?

**Comment by octachrome** [comment]
You need to install the couchdb server. It's a Windows app that you download and install from their website.

**Comment by octachrome** [comment]
I finally fixed the docs for this.
