### ISSUE TITLE
trying to run this on k8s as a 2 tier application

### ISSUE THREAD

**Issue by lxie123** [octachrome/treason#33]
How do I configure this node application to use a different host for the  database. I keep getting the following:

I want to run couchdb as a separate container.
Failed to initialise database(s)
Error: connect ECONNREFUSED 127.0.0.1:5984
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5984
}

I want it to use "coup-db" instead of 127.0.0.1

**Comment by octachrome** [comment]
In `server.js`:

    var connection = new(cradle.Connection)({
        host: 'coup-db'
    });

**Comment by Trevor-Welch** [comment]
Is this issue closed?

**Comment by octachrome** [comment]
Couch is no longer needed in the latest master.
